### ISSUE TITLE
Not possible to bind several modules to same element?

### ISSUE THREAD

**Issue by OlofFredriksson** [brunschgi/terrificjs#31]
Hello! I have been working with terrific js for a while, and have to say first that it works quite good. :-) 

However, I wonder if it's possible to bind several modules to same element, I created a test page which shows whats happens when trying to do this: 
http://jsfiddle.net/olof/tArGp/2/

As you can see, on element 3, I bind both mod-logo and mod-test to the div, but it only trigger the last module. Same happens with 4, but mod-logo is loaded instead.

Am I doing something wrong here, or is this a limitation with terrificjs?

Thanks!

// Olof

**Comment by brunschgi** [comment]
Hi Olof

First of all: You aren't doing something wrong here :-)  But what you are trying to achieve is not possible by using multiple different modules. As per definition – from Nicholas Zakas back in 2009 – a module is a «independent unit of functionality» it is not possible per design to have multiple modules on the same DOM element. 

But maybe there is another approach that could help you:
1. If you want to extend the functionality of one of your modules you could use terrific js skins http://terrifically.org/api/skin/ instead
2. If you are trying to bind more generic logic – i.e. accordions, tabs etc, that could be used all over the place and even nested into other modules – you could go with a global modules that does the work for you http://terrifically.org/api/application/#registerglobalmodule (of course you could do that also by class conventions instead of registering the global module manually)

Hope this helps & Cheers
Remo

**Comment by OlofFredriksson** [comment]
Hello Remo, and thanks for your fast response! In my case, i could fix my problems with using Skins instead of modules, but will also do some reading about with the global modules.

Closing this issue for now, but i maybe have more questions about terrific in the future. ;)

Thanks again

Olof
