### ISSUE TITLE
Add function to return module by name

### ISSUE THREAD

**Issue by tigerclaw-az** [brunschgi/terrificjs#69]
Instead of only allowing getModuleById(), can there also be a function for getModuleByName()?

**Comment by brunschgi** [comment]
Hi ejwaibel
The getModuleByName() method would potentially return a list of module instances instead of a single instance. As you would like – at least most of the time – to have access to a single instance only, we are not going to include this in the official API. However, you can achieve this very easily by doing something like:

```
var nodes = [].slice.call(document.querySelectorAll('[data-t-name]'));
var instances = [];
nodes.forEach(function (ctx) {
  var id = ctx.getAttribute('data-t-id');
  if(id) {
    instances.push(this.sandbox.getModuleById(id));
  }
}.bind(this));
```

Hope this helps
Best, Remo
