### ISSUE TITLE
lazy initialization of modules

### ISSUE THREAD

**Issue by brunschgi** [brunschgi/terrificjs#8]
Modules should have a "tag" (eg. data-ignore="true") to ignore them in the initial TerrificJS bootstrap. This makes it possible to reduce the initial workload and to lazy init the modules on demand (eg. after scrolling beyond the fold, on click for rarely used functionality etc.).

**Comment by MarcDiethelm** [comment]
How about data-defer, similar to how scripts can be loaded in HTML5? (Don't know if async is feasible...)

> There are three possible modes that can be selected using these attributes. If the async attribute is present, then the script will be executed asynchronously, as soon as it is available. If the async attribute is not present but the defer attribute is present, then the script is executed when the page has finished parsing. If neither attribute is present, then the script is fetched and executed immediately, before the user agent continues parsing the page.

http://www.whatwg.org/specs/web-apps/current-work/multipage/scripting-1.html#the-script-element

**Comment by brunschgi** [comment]
Hi Marc

Cool idea! The renaming from data-ignore to data-defer makes sense for me (though it has not exactly the same meaning as defer in the script tag). Think I will go with data-defer ;-)

The async thing has been in my mind for a while ;-) Let's say you wouldn't include all the terrific module scripts on your page… this would give you the possibilty to only load the terrific module scripts that are really on your page.

In my opinion, there are 2 scenarios:

Scenario 1: 1 HTTP request / module
- could lead to many many requests
- the module scripts are cacheable for other pages

Scenario 2: 1 HTTP request for all modules on the page
-  backend logic needed for specific concatenation
-  the given script is probably only usable on a specific page (as the same module combination is not given on another page)
- only 1 request 

What do you think? Do you see another possible scenario?

Looking forward to your answer

**Comment by MarcDiethelm** [comment]
Ah, I wasn't aware that you're also talking about lazy **loading**. :)

Ok... This would be insanely cool! Reminds me about something I talked about on Lea Verou's blog some time ago:
http://lea.verou.me/2012/01/what-we-still-can%e2%80%99t-do-client-side/#comment-406913048
Although it seems that proving a no-js (or even a no-ajax) fallback for this content would be impossible...

Apart form that little snag... :) I prefer scenario 1. The request seems justified as it speeds up the initial heavy page load. And with HTTP 1.1 we shouldn't worry about the amount of requests _that_ much anymore (as long as they are not for 3kB Gifs or something like that.)
Scenario 2 adds quite a bit of complexity that might get painful when using certain old and buggy browsers... Also if you want to do async, I think you should just let each module do it's own thing.

In order to provide dependency management between lazy-loaded modules some magic would be needed. Say, I like to check if a module exists on the page and/or register a callback in the application that tells when it does.

That's my 50 cent.

**Comment by brunschgi** [comment]
Hi Marc

Interesting idea on the lea.verou blog!

I re-thought and discussed the whole lazy loading / lazy initialization thing. As in v2.0 all dependency management stuff is stripped away (and can now be done with your preferred script loader, eg. yepnope.js, require.js etc.), I think lazy loading of modules should better be done separately outside of the TerrificJS core. 
With the Terrific Composer it is as simple as disabling the include of the base.js and iterate over all mods and load the appropriate module javascript file. In this manner it can even be done for any DOM part of your choice independently.

Nonetheless I think the lazy initialization is still needed (for the reasons described in the first place). But for that data-defer is not the correct term (as the script is not executed when everything is loaded… it is executed on demand, eg. onclick, onscroll etc.). So the only point to this, is to ignore the module in the TerrificJS bootstrap.

Therefore I still think data-ignore="true|false" would be more logically.

What do you think?

Cheers,
Remo
